# Generated by Django 3.0.8 on 2020-07-15 06:39

from django.db import migrations, models
import attachments.models


def assign_requires_watermark(apps, schema_editor):
    Attachment = apps.get_model('attachments', 'Attachment')
    Attachment.objects.all().update(requires_watermark=False)
    

class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0005_requires_watermark'),
    ]

    operations = [
        migrations.RunPython(
            code=assign_requires_watermark,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
